# Generated by Django 5.1.5 on 2025-03-18 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_requestchatgpt_alter_documentembedding_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentembedding',
            old_name='text',
            new_name='name',
        ),
    ]
