# Generated by Django 5.1.5 on 2025-04-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_text_documentembedding_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestchatgpt',
            name='similarity',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestchatgpt',
            name='created_at',
            field=models.DateTimeField(default=0.0),
        ),
    ]
