# Generated by Django 5.1.5 on 2025-04-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_requestchatgpt_similarity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestchatgpt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
