# Generated by Django 5.1.5 on 2025-01-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChairState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('broken_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeskState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('broken_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('broken_status', models.BooleanField(default=False)),
                ('equipment_type', models.CharField(max_length=50)),
            ],
        ),
    ]
