# Generated by Django 5.1.5 on 2025-04-20 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Located',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name', models.CharField(max_length=100)),
                ('building_name', models.CharField(max_length=100)),
                ('room_name', models.CharField(max_length=100)),
                ('coordinates', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('angle', models.FloatField()),
                ('is_door_open', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('category', models.CharField(choices=[('STRUCTURE', '구조물'), ('FACILITY', '설비'), ('FURNITURE', '가구'), ('ELECTRONIC', '전자기기'), ('OTHER', '기타')], default='OTHER', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('state', models.CharField(choices=[('NORMAL', '정상'), ('BROKEN', '고장'), ('UNDER_REPAIR', '수리 중'), ('NEEDS_REPLACEMENT', '교체 필요')], default='NORMAL', max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='infrastructure.located')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('HIGH', '긴급'), ('MEDIUM', '보통'), ('LOW', '낮음')], default='MEDIUM', max_length=10)),
                ('failure_type', models.CharField(choices=[('STRUCTURAL', '구조적 손상'), ('ELECTRICAL', '전기 문제'), ('MECHANICAL', '기계적 문제'), ('OTHER', '기타')], default='OTHER', max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='infrastructure.asset')),
            ],
        ),
        migrations.CreateModel(
            name='RepairHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repaired_by', models.CharField(max_length=100)),
                ('repair_details', models.TextField()),
                ('repaired_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repair', to='infrastructure.maintenancereport')),
            ],
        ),
    ]
