# Generated by Django 5.1.5 on 2025-02-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChairState',
        ),
        migrations.AddField(
            model_name='deskstate',
            name='broken_chairState',
            field=models.BooleanField(default=False),
        ),
    ]
