# Generated by Django 5.1.5 on 2025-05-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='airconditioner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='is_person_there',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='is_door_open',
            field=models.BooleanField(default=False),
        ),
    ]
