# Generated by Django 5.1.5 on 2025-02-03 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_delete_chairstate_deskstate_broken_chairstate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deskstate',
            old_name='broken_chairState',
            new_name='broken_chair_state',
        ),
    ]
