# Generated by Django 5.1.5 on 2025-03-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_asset_building_campus_floor_maintenancereport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='failure_type',
            field=models.CharField(choices=[('STRUCTURAL', '구조적 손상'), ('ELECTRICAL', '전기 문제'), ('MECHANICAL', '기계적 문제'), ('OTHER', '기타')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
